import "./globals.css";
import { Onest } from "next/font/google";

const onest = Onest({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-onest",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-full min-h-screen font-onest antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
