
export const courseData = [
  {
    title: 'Foundation of Sleep: Sleep Science and Sleep Disorders',
    level: 'Beginner',
    category: 'Nutrition and Diet',
    rating: 4.8,
    numberOfRatings: 566,
    duration: '6h 34m',
    lessons: 3,
    instructor: 'Kilian Murphe',
    price: 40,
    enrolled: false,
    backgroundImage: '/assets/courses/backgrounds/course1.png',
    instructorImage: '/assets/courses/instructors/instructor1.png'
  },
  {
    title: 'Parenting in the Digital Age: Navigating Screen Time',
    level: 'Intermediate',
    category: 'Health and Wellness',
    rating: 4.9,
    numberOfRatings: 456,
    duration: '6h 34m',
    lessons: 3,
    instructor: 'Sarah Hopkins',
    price: 50,
    enrolled: false,
    backgroundImage: '/assets/courses/backgrounds/course2.png',
    instructorImage: '/assets/courses/instructors/instructor2.png'
  },
  {
    title: 'Holistic Health: Integrating Mind, Body, and Spirit',
    level: 'Beginner',
    category: 'Nutrition and Diet',
    rating: 4.8,
    numberOfRatings: 399,
    duration: '6h 34m',
    lessons: 3,
    instructor: 'Luna Karim',
    price: 40,
    enrolled: true,
    backgroundImage: '/assets/courses/backgrounds/course3.png',
    instructorImage: '/assets/courses/instructors/instructor3.png'
  },
  {
    title: 'Introduction to healthy Diet and Nutrition',
    level: 'Beginner',
    category: 'Nutrition and Diet',
    rating: 4.8,
    numberOfRatings: 566,
    duration: '6h 34m',
    lessons: 3,
    instructor: 'Kate Winslate',
    price: 40,
    enrolled: false,
    backgroundImage: '/assets/courses/backgrounds/course4.png',
    instructorImage: '/assets/courses/instructors/instructor4.png'
  },
  {
    title: 'Holistic Health: Integrating Mind, Body, and Spirit (Part-2)',
    level: 'Intermediate',
    category: 'Nutrition and Diet',
    rating: 4.8,
    numberOfRatings: 399,
    duration: '6h 34m',
    lessons: 3,
    instructor: 'Luna Karim',
    price: 40,
    enrolled: false,
    backgroundImage: '/assets/courses/backgrounds/course3.png',
    instructorImage: '/assets/courses/instructors/instructor3.png'
  },
];